### LIBRERIE

In [1]:
import pandas as pd
import numpy as np
import scipy.stats

### CARICO IL DATASET IN MEMORIA

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/mariocuomo/progettoSII/main/ratings.csv')
df_film = pd.read_csv('https://raw.githubusercontent.com/mariocuomo/progettoSII/main/movies.csv')

In [3]:
### CREO RATING MATRIX

In [4]:
rating_matrix = df.pivot(index = 'userId', columns = 'movieId', values = 'rating').fillna(0)

In [5]:
rating_matrix

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.5,0.0,0.0,0.0,0.0,0.0,2.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,2.5,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
609,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,5.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### PER OGNI COLONNA (film) CALCOLO L'ENTROPIA

In [6]:
lst=[]
for (colname,colval) in rating_matrix.iteritems():
    lst.append((colname,scipy.stats.entropy(colval)))
lst.sort(key = lambda x: x[1], reverse=True)

In [7]:
lst[2]

(296, 5.695938745641419)

### ARRICCHISCO LA STAMPA CON LE INFORMAZIONI RIGUARDO IL TITOLO E IL GENERE

In [8]:
ll = []
for item in lst[0:50]:
    rslt_df = df_film[df_film['movieId'] == (item[0])]
    title=rslt_df.iloc[0]['title']
    genere=rslt_df.iloc[0]['genres'].replace("|", ",")
    score = item[1]
    ll.append([title, score, genere])
suggestions = pd.DataFrame(ll, columns = ['TITOLO', 'ENTROPIA', 'GENERE'])

In [9]:
suggestions

,TITOLO,ENTROPIA,GENERE
0,Forrest Gump (1994),5.773944,"Comedy,Drama,Romance,War"
1,"Shawshank Redemption, The (1994)",5.744399,"Crime,Drama"
2,Pulp Fiction (1994),5.695939,"Comedy,Crime,Drama,Thriller"
3,"Silence of the Lambs, The (1991)",5.606308,"Crime,Horror,Thriller"
4,"Matrix, The (1999)",5.593650,"Action,Sci-Fi,Thriller"
5,Star Wars: Episode IV - A New Hope (1977),5.501065,"Action,Adventure,Sci-Fi"
6,Jurassic Park (1993),5.444037,"Action,Adventure,Sci-Fi,Thriller"
7,Braveheart (1995),5.434879,"Action,Drama,War"
8,Terminator 2: Judgment Day (1991),5.379976,"Action,Sci-Fi"
9,Schindler's List (1993),5.360749,"Drama,War"
10,Fight Club (1999),5.359550,"Action,Crime,Drama,Thriller"
11,Toy Story (1995),5.345934,"Adventure,Animation,Children,Comedy,Fantasy"
12,Star Wars: Episode V - The Empire Strikes Back...,5.329296,"Action,Adventure,Sci-Fi"
13,"Usual Suspects, The (1995)",5.298119,"Crime,Mystery,Thriller"
14,American Beauty (1999),5.283691,"Drama,Romance"
15,Seven (a.k.a. Se7en) (1995),5.282052,"Mystery,Thriller"
16,Raiders of the Lost Ark (Indiana Jones and the...,5.277533,"Action,Adventure"
17,Apollo 13 (1995),5.275758,"Adventure,Drama,IMAX"
18,Independence Day (a.k.a. ID4) (1996),5.262063,"Action,Adventure,Sci-Fi,Thriller"
19,"Lord of the Rings: The Fellowship of the Ring,...",5.257562,"Adventure,Fantasy"
20,Star Wars: Episode VI - Return of the Jedi (1983),5.253480,"Action,Adventure,Sci-Fi"
21,"Godfather, The (1972)",5.231859,"Crime,Drama"
22,"Fugitive, The (1993)",5.225949,Thriller
23,Batman (1989),5.216270,"Action,Crime,Thriller"
24,Saving Private Ryan (1998),5.215126,"Action,Drama,War"
25,"Lord of the Rings: The Two Towers, The (2002)",5.208469,"Adventure,Fantasy"
26,"Lord of the Rings: The Return of the King, The...",5.196204,"Action,Adventure,Drama,Fantasy"
27,Aladdin (1992),5.180024,"Adventure,Animation,Children,Comedy,Musical"
28,Fargo (1996),5.176769,"Comedy,Crime,Drama,Thriller"
29,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),5.155398,"Mystery,Sci-Fi,Thriller"
30,"Sixth Sense, The (1999)",5.151769,"Drama,Horror,Mystery"
31,True Lies (1994),5.146021,"Action,Adventure,Comedy,Romance,Thriller"
32,"Lion King, The (1994)",5.123357,"Adventure,Animation,Children,Drama,Musical,IMAX"
33,Back to the Future (1985),5.115548,"Adventure,Comedy,Sci-Fi"
34,Speed (1994),5.103984,"Action,Romance,Thriller"
35,Shrek (2001),5.102806,"Adventure,Animation,Children,Comedy,Fantasy,Ro..."
36,Gladiator (2000),5.097838,"Action,Adventure,Drama"
37,Dances with Wolves (1990),5.073214,"Adventure,Drama,Western"
38,Men in Black (a.k.a. MIB) (1997),5.067082,"Action,Comedy,Sci-Fi"
39,Mission: Impossible (1996),5.051767,"Action,Adventure,Mystery,Thriller"
40,Memento (2000),5.039705,"Mystery,Thriller"
41,Ace Ventura: Pet Detective (1994),5.013968,Comedy
42,"Mask, The (1994)",5.001283,"Action,Comedy,Crime,Fantasy"
43,"Dark Knight, The (2008)",4.988428,"Action,Crime,Drama,IMAX"
44,Pirates of the Caribbean: The Curse of the Bla...,4.976916,"Action,Adventure,Comedy,Fantasy"
45,Beauty and the Beast (1991),4.958397,"Animation,Children,Fantasy,Musical,Romance,IMAX"
46,Alien (1979),4.950933,"Horror,Sci-Fi"
47,Die Hard (1988),4.944910,"Action,Crime,Thriller"
48,Groundhog Day (1993),4.937454,"Comedy,Fantasy,Romance"
49,"Princess Bride, The (1987)",4.935701,"Action,Adventure,Comedy,Fantasy,Romance"